version: '2'
services:
    python:
        build:
            context: .
            dockerfile: ./dockerfiles/Dockerfile-cpu
        container_name : faster_rcnn 
        image: "tuananhbk/mlpractice:cpu" 
        ports:
            - "8889:8889"
        volumes:
            - ".:/data"
        shm_size: '10gb'
        user: anh
        working_dir: /data
        tty: true
        command: jupyter notebook --ip=0.0.0.0 --port=8889 --NotebookApp.password='sha1:4018b457b8a9:84c65a176a549c58609c3cf38fa50b4b1b12b808'
    anaconda:
        image: "tuananhbk/mlpractice:cpu"
        ports:
            - "8000:8000"
        volumes:
            - "./faster_rcnn:/data/faster_rcnn" 
        working_dir: ${PWD}
        user: anh
        tty: true