services:
  anaconda:
    depends_on:
    - python
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    entrypoint: /opt/anaconda/anaconda_server/docker/start python 19361 docker /opt/anaconda
    image: tuananhbk/mlpractice:gpu
    ports:
    - 19361:19361
    tty: true
    user: root
    volumes:
    - /home/anh/.config/sublime-text-3/Packages/Anaconda:/opt/anaconda
    - ./faster_rcnn:/data/faster_rcnn
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  crayon:
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: alband/crayon
    ports:
    - 8888:8888
    - 8889:8889
    volumes:
    - nvidia_driver_375.66:/usr/local/nvidia:ro
  python:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: jupyter notebook --ip=0.0.0.0 --port=8081
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    image: tuananhbk/mlpractice:gpu
    links:
    - crayon
    ports:
    - 8081:8081
    tty: true
    user: anh
    volumes:
    - .:/data
    - nvidia_driver_375.66:/usr/local/nvidia:ro
    working_dir: /data
version: '2'
volumes:
  nvidia_driver_375.66:
    external: true
